name: Build WASM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: "latest"
      - name: Build wasm
        run: wasm-pack build --target web
      - name: Download pkg deps
        run: cd pkg && npm i && cd .. && cp pkg/sp_format_bg.wasm playground/sp_format_bg.wasm && cp pkg/node_modules/web-tree-sitter/tree-sitter.wasm playground/tree-sitter.wasm
      - name: Setup Playground
        run: cd playground && npm i && npm run build
      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v0.1.0
          artifacts: "pkg/sp_format_bg.wasm"
          body: ""
          draft: false
          allowUpdates: true
          prerelease: false
          replacesArtifacts: true
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: playground/dist
